Repository FACG5/Marna-House, pull requests merged in 2018-10, with the labels that each got.

#20 Initial server
  .eslintrc.json
  .gitignore
  package.json
  src/app.js
  src/controllers/index.js
  src/index.js
Labels: waiting-review

#22 Scheme
  .gitignore
  src/model/database/db_build.sql
Labels: approved

#24 made db_connection #2
  package.json
  src/model/database/db_connection.js
Labels: waiting-review

#25 Add User Query
  package.json
  src/model/database/db_build.js
  src/model/queries/users.js
  test/testDB.js
Labels: waiting-review

#26 Queries
  src/model/queries/rooms.js
  src/model/queries/users.js
  test/testDB.js
Labels: waiting-review

#28 Admin Table
  src/model/database/db_build.sql
Labels: waiting-review

#31 getRoom query
  src/model/database/db_connection.js
  src/model/queries/rooms.js
  test/testDB.js
Labels: approved

#30 home page view header & footer #13
  package-lock.json
  public/css/style.css
  src/app.js
  src/controllers/home.js
  src/controllers/index.js
  src/views/home.hbs
  src/views/layouts/error.hbs
  src/views/layouts/main.hbs
  src/views/partials/footer.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
Labels: waiting-review

#33 Eslint Config
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  src/model/database/db_build.js
  src/model/database/db_connection.js
  src/model/queries/rooms.js
  src/model/queries/users.js
  test/testDB.js
Labels: approved

#34 make updateRoom Query #11
  src/model/database/db_build.js
  src/model/database/db_build.sql
  src/model/database/db_fackData.js
  src/model/database/fackData.sql
  src/model/queries/rooms.js
  src/model/queries/users.js
  src/model/queries/utilities.js
  test/testDB.js
Labels: Done

#37 addReservation Query #12
  src/model/queries/reservations.js
  test/testDB.js
Labels: approved

#40 Add reservation
  public/js/home.js
  src/controllers/home.js
  src/controllers/index.js
  src/views/layouts/main.hbs
Labels: Done, approved

#41 edit available rooms query
  src/model/database/fackData.sql
  src/model/queries/rooms.js
  src/model/queries/utilities.js
  test/testDB.js
Labels: approved

#42 Edit home
  .eslintrc.json
  package.json
  public/css/home.css
  public/css/homeHeader.css
  public/css/loading.css
  public/css/login.css
  public/css/model.css
  public/css/signup.css
  public/js/home.js
  public/js/login.js
  public/js/signup.js
  src/app.js
  src/controllers/home.js
  src/controllers/index.js
  src/controllers/login.js
  src/controllers/signup.js
  src/middlewares/unlockCookie.js
  src/model/database/db_build.sql
  src/model/database/fackData.sql
  src/model/queries/reservations.js
  src/model/queries/rooms.js
  src/model/queries/users.js
  src/model/queries/utilities.js
  src/views/home.hbs
  src/views/layouts/auth.hbs
  src/views/layouts/main.hbs
  src/views/login.hbs
  src/views/partials/footer.hbs
  src/views/partials/head.hbs
  src/views/partials/headAuth.hbs
  src/views/partials/header.hbs
  src/views/signup.hbs
Labels: approved
